<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>728d345a-8a84-4e2e-9ef1-5beaa432042a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MongoDB.Bson" Version="3.5.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.5.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevLearning.AuthorAPI\DevLearning.AuthorAPI.csproj" />
    <ProjectReference Include="..\DevLearning.Models\DevLearning.Models.csproj" />
    <ProjectReference Include="..\DevLearning.CategoryAPI\DevLearning.CategoryAPI.csproj" />
    <ProjectReference Include="..\DevLearning.StudentAPI\DevLearning.StudentAPI.csproj" />
  </ItemGroup>

</Project>
